#!/bin/bash

echo "target: $1, erase: $2"
echo "Current working directory: $(pwd)"

export target=rmp_core_generic

if [ "$1" == "$target" ]; then
    
    echo "RMP Core Generic"

    if [$2 == "erase"]; then
        echo "Erasing Flash"
        python /opt/esp/idf/components/esptool_py/esptool/esptool.py \
        -b 460800 --before default_reset --after hard_reset --chip esp32 erase_flash
    fi

python /opt/esp/idf/components/esptool_py/esptool/esptool.py \
 -b 460800 --before default_reset --after hard_reset --chip esp32 \
  write_flash --flash_mode dio --flash_size 4MB --flash_freq 40m \
  0x1000 ./release/rmp_core_generic_bootloader.bin 0x8000 ./release/rmp_core_generic_partition-table.bin 0x10000 ./release/rmp_core_generic.bin

fi

export target="rmp_core_s3"
if [ "$1" == "$target" ]; then
    echo "RMP Core S3"

    if [ $2 == "erase" ]; then
        echo "Erasing Flash"
        python /opt/esp/idf/components/esptool_py/esptool/esptool.py \
        -b 460800 --before default_reset --after hard_reset --chip esp32s3 erase_flash
    fi

    python /opt/esp/idf/components/esptool_py/esptool/esptool.py \
    -b 460800 --before default_reset --after no_reset --chip esp32s3 \
    write_flash  --flash_mode dio --flash_size 16MB --flash_freq 80m \
    0x0 ./release/rmp_core_s3_bootloader.bin 0x8000 ./release/rmp_core_s3_partition-table.bin 0x10000 ./release/rmp_core_s3.bin
fi

