#!/bin/sh


python /opt/esp/idf/components/esptool_py/esptool/esptool.py \
 -b 460800 --before default_reset --after no_reset --chip esp32s3 \
  write_flash  --flash_mode dio --flash_size 16MB --flash_freq 80m \
  0x0 ./release/bootloader.bin 0x8000 ./release/partition-table.bin 0x10000 ./release/micropython_RMP_WROOM1_S3.bin
