_TYPE_DEFS = {
    'Bool': ('Bool', 'std_msgs::msg', (('data', 'bool', (), False, False, 0),)),
    'Byte': ('Byte', 'std_msgs::msg', (('data', 'byte', (), False, False, 0),)),
    'ByteMultiArray': ('ByteMultiArray', 'std_msgs::msg', (('layout', 'MultiArrayLayout', (('dim', 'MultiArrayDimension', (('label', 'string', (), False, False, 0), ('size', 'uint32', (), False, False, 0), ('stride', 'uint32', (), False, False, 0)), False, True, 0), ('data_offset', 'uint32', (), False, False, 0)), False, False, 0), ('data', 'byte', (), False, True, 0))),
    'Char': ('Char', 'std_msgs::msg', (('data', 'char', (), False, False, 0),)),
    'ColorRGBA': ('ColorRGBA', 'std_msgs::msg', (('r', 'float32', (), False, False, 0), ('g', 'float32', (), False, False, 0), ('b', 'float32', (), False, False, 0), ('a', 'float32', (), False, False, 0))),
    'Empty': ('Empty', 'std_msgs::msg', ()),
    'Float32': ('Float32', 'std_msgs::msg', (('data', 'float32', (), False, False, 0),)),
    'Float32MultiArray': ('Float32MultiArray', 'std_msgs::msg', (('layout', 'MultiArrayLayout', (('dim', 'MultiArrayDimension', (('label', 'string', (), False, False, 0), ('size', 'uint32', (), False, False, 0), ('stride', 'uint32', (), False, False, 0)), False, True, 0), ('data_offset', 'uint32', (), False, False, 0)), False, False, 0), ('data', 'float32', (), False, True, 0))),
    'Float64': ('Float64', 'std_msgs::msg', (('data', 'float64', (), False, False, 0),)),
    'Float64MultiArray': ('Float64MultiArray', 'std_msgs::msg', (('layout', 'MultiArrayLayout', (('dim', 'MultiArrayDimension', (('label', 'string', (), False, False, 0), ('size', 'uint32', (), False, False, 0), ('stride', 'uint32', (), False, False, 0)), False, True, 0), ('data_offset', 'uint32', (), False, False, 0)), False, False, 0), ('data', 'float64', (), False, True, 0))),
    'Header': ('Header', 'std_msgs::msg', (('stamp', 'Time', (), False, False, 0), ('frame_id', 'string', (), False, False, 0))),
    'Int16': ('Int16', 'std_msgs::msg', (('data', 'int16', (), False, False, 0),)),
    'Int16MultiArray': ('Int16MultiArray', 'std_msgs::msg', (('layout', 'MultiArrayLayout', (('dim', 'MultiArrayDimension', (('label', 'string', (), False, False, 0), ('size', 'uint32', (), False, False, 0), ('stride', 'uint32', (), False, False, 0)), False, True, 0), ('data_offset', 'uint32', (), False, False, 0)), False, False, 0), ('data', 'int16', (), False, True, 0))),
    'Int32': ('Int32', 'std_msgs::msg', (('data', 'int32', (), False, False, 0),)),
    'Int32MultiArray': ('Int32MultiArray', 'std_msgs::msg', (('layout', 'MultiArrayLayout', (('dim', 'MultiArrayDimension', (('label', 'string', (), False, False, 0), ('size', 'uint32', (), False, False, 0), ('stride', 'uint32', (), False, False, 0)), False, True, 0), ('data_offset', 'uint32', (), False, False, 0)), False, False, 0), ('data', 'int32', (), False, True, 0))),
    'Int64': ('Int64', 'std_msgs::msg', (('data', 'int64', (), False, False, 0),)),
    'Int64MultiArray': ('Int64MultiArray', 'std_msgs::msg', (('layout', 'MultiArrayLayout', (('dim', 'MultiArrayDimension', (('label', 'string', (), False, False, 0), ('size', 'uint32', (), False, False, 0), ('stride', 'uint32', (), False, False, 0)), False, True, 0), ('data_offset', 'uint32', (), False, False, 0)), False, False, 0), ('data', 'int64', (), False, True, 0))),
    'Int8': ('Int8', 'std_msgs::msg', (('data', 'int8', (), False, False, 0),)),
    'Int8MultiArray': ('Int8MultiArray', 'std_msgs::msg', (('layout', 'MultiArrayLayout', (('dim', 'MultiArrayDimension', (('label', 'string', (), False, False, 0), ('size', 'uint32', (), False, False, 0), ('stride', 'uint32', (), False, False, 0)), False, True, 0), ('data_offset', 'uint32', (), False, False, 0)), False, False, 0), ('data', 'int8', (), False, True, 0))),
    'MultiArrayDimension': ('MultiArrayDimension', 'std_msgs::msg', (('label', 'string', (), False, False, 0), ('size', 'uint32', (), False, False, 0), ('stride', 'uint32', (), False, False, 0))),
    'MultiArrayLayout': ('MultiArrayLayout', 'std_msgs::msg', (('dim', 'MultiArrayDimension', (('label', 'string', (), False, False, 0), ('size', 'uint32', (), False, False, 0), ('stride', 'uint32', (), False, False, 0)), False, True, 0), ('data_offset', 'uint32', (), False, False, 0))),
    'String': ('String', 'std_msgs::msg', (('data', 'string', (), False, False, 0),)),
    'UInt16': ('UInt16', 'std_msgs::msg', (('data', 'uint16', (), False, False, 0),)),
    'UInt16MultiArray': ('UInt16MultiArray', 'std_msgs::msg', (('layout', 'MultiArrayLayout', (('dim', 'MultiArrayDimension', (('label', 'string', (), False, False, 0), ('size', 'uint32', (), False, False, 0), ('stride', 'uint32', (), False, False, 0)), False, True, 0), ('data_offset', 'uint32', (), False, False, 0)), False, False, 0), ('data', 'uint16', (), False, True, 0))),
    'UInt32': ('UInt32', 'std_msgs::msg', (('data', 'uint32', (), False, False, 0),)),
    'UInt32MultiArray': ('UInt32MultiArray', 'std_msgs::msg', (('layout', 'MultiArrayLayout', (('dim', 'MultiArrayDimension', (('label', 'string', (), False, False, 0), ('size', 'uint32', (), False, False, 0), ('stride', 'uint32', (), False, False, 0)), False, True, 0), ('data_offset', 'uint32', (), False, False, 0)), False, False, 0), ('data', 'uint32', (), False, True, 0))),
    'UInt64': ('UInt64', 'std_msgs::msg', (('data', 'uint64', (), False, False, 0),)),
    'UInt64MultiArray': ('UInt64MultiArray', 'std_msgs::msg', (('layout', 'MultiArrayLayout', (('dim', 'MultiArrayDimension', (('label', 'string', (), False, False, 0), ('size', 'uint32', (), False, False, 0), ('stride', 'uint32', (), False, False, 0)), False, True, 0), ('data_offset', 'uint32', (), False, False, 0)), False, False, 0), ('data', 'uint64', (), False, True, 0))),
    'UInt8': ('UInt8', 'std_msgs::msg', (('data', 'uint8', (), False, False, 0),)),
    'UInt8MultiArray': ('UInt8MultiArray', 'std_msgs::msg', (('layout', 'MultiArrayLayout', (('dim', 'MultiArrayDimension', (('label', 'string', (), False, False, 0), ('size', 'uint32', (), False, False, 0), ('stride', 'uint32', (), False, False, 0)), False, True, 0), ('data_offset', 'uint32', (), False, False, 0)), False, False, 0), ('data', 'uint8', (), False, True, 0))),
}
