from rosmicropy_interfaces import Message
from ._types import _TYPE_DEFS

class Transition(Message):
    _TYPE_NAME = 'Transition'
    _TYPE_DEF = _TYPE_DEFS['Transition']
    _fields_and_field_types = {'id': 'uint8', 'label': 'string'}
    TRANSITION_CREATE = 0
    TRANSITION_CONFIGURE = 1
    TRANSITION_CLEANUP = 2
    TRANSITION_ACTIVATE = 3
    TRANSITION_DEACTIVATE = 4
    TRANSITION_UNCONFIGURED_SHUTDOWN = 5
    TRANSITION_INACTIVE_SHUTDOWN = 6
    TRANSITION_ACTIVE_SHUTDOWN = 7
    TRANSITION_DESTROY = 8
    TRANSITION_ON_CONFIGURE_SUCCESS = 10
    TRANSITION_ON_CONFIGURE_FAILURE = 11
    TRANSITION_ON_CONFIGURE_ERROR = 12
    TRANSITION_ON_CLEANUP_SUCCESS = 20
    TRANSITION_ON_CLEANUP_FAILURE = 21
    TRANSITION_ON_CLEANUP_ERROR = 22
    TRANSITION_ON_ACTIVATE_SUCCESS = 30
    TRANSITION_ON_ACTIVATE_FAILURE = 31
    TRANSITION_ON_ACTIVATE_ERROR = 32
    TRANSITION_ON_DEACTIVATE_SUCCESS = 40
    TRANSITION_ON_DEACTIVATE_FAILURE = 41
    TRANSITION_ON_DEACTIVATE_ERROR = 42
    TRANSITION_ON_SHUTDOWN_SUCCESS = 50
    TRANSITION_ON_SHUTDOWN_FAILURE = 51
    TRANSITION_ON_SHUTDOWN_ERROR = 52
    TRANSITION_ON_ERROR_SUCCESS = 60
    TRANSITION_ON_ERROR_FAILURE = 61
    TRANSITION_ON_ERROR_ERROR = 62
    TRANSITION_CALLBACK_SUCCESS = 97
    TRANSITION_CALLBACK_FAILURE = 98
    TRANSITION_CALLBACK_ERROR = 99

    def __init__(self, id=None, label=None):
        self['id'] = 0 if id is None else id
        self['label'] = '' if label is None else label

dataMap = Transition.get_data_map()
